### ISSUE TITLE
Exception raised: Errno::ENOENT

### ISSUE THREAD

**Issue by owenstrevor** [bridgetownrb/bridgetown-slim#2]
```
[Bridgetown]   Conversion error: Bridgetown::Converters::SlimTemplates encountered an error while converting `_posts/2022-11-08-welcome-to-bridgetown.md'
[Bridgetown]   Exception raised: Errno::ENOENT
[Bridgetown] No such file or directory @ rb_sysopen - /Users/owens/Code/cpsite/src/_partials/_head.slim 
[Bridgetown]                  1: /Users/owens/.rvm/gems/ruby-3.1.2/gems/tilt-2.0.11/lib/tilt/template.rb:236:in `initialize'
[Bridgetown]                  2: /Users/owens/.rvm/gems/ruby-3.1.2/gems/tilt-2.0.11/lib/tilt/template.rb:236:in `open'
[Bridgetown]                  3: /Users/owens/.rvm/gems/ruby-3.1.2/gems/tilt-2.0.11/lib/tilt/template.rb:236:in `read_template_file'
[Bridgetown]                  4: /Users/owens/.rvm/gems/ruby-3.1.2/gems/tilt-2.0.11/lib/tilt/template.rb:85:in `block in initialize'
[Bridgetown]                  5: /Users/owens/.rvm/gems/ruby-3.1.2/gems/tilt-2.0.11/lib/tilt/template.rb:86:in `initialize'
[Bridgetown]          Backtrace: Use the --trace option for complete information.
```
My slim template (default.slim)
```
doctype html
html lang="en"
  head
    = render "head", metadata: site.metadata, title: resource.data.title
  body
    main
      | Hello
```

Hi I'm new to bridgetown and just trying to get running!

**Comment by AnomalousBit** [comment]
I'm new to bridgetown too and maybe this will come back to bite me, but I fixed this by renaming the `_components` directory to `_partials`. The calls to `render()` inside a slim template using bridgetown-slim don't appear to look into the `_components` directory by default.

I think there is a configuration option to add directories to the search path but I'm not there yet.

**Comment by jaredcwhite** [comment]
Apologies @owenstrevor for missing this post back in November. I'm closing the issue now but feel free to post in our main GitHub Discussions or in our Discord server if you need further assistance.
